services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: t4school
      POSTGRES_PASSWORD: t4school
      POSTGRES_DB: t4school
    ports:
      - "5432:5432"
    volumes:
      - t4school_pgdata:/var/lib/postgresql/data

volumes:
  t4school_pgdata:
