import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { StatsCard } from '@/components/dashboard/StatsCard';
import { LessonCard } from '@/components/lessons/LessonCard';
import { CreateLessonModal } from '@/components/lessons/CreateLessonModal';
import { Lesson } from '@/types';
import {
  Calendar,
  Users,
  Clock,
  Bell,
  Plus,
  ArrowRight,
  TrendingUp,
  AlertTriangle,
  Loader2,
} from 'lucide-react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AulasService } from '@/lib/aulas.service';
import { Aula } from '@/types';
import { listarAlunos, listarAlertasAlunos } from '@/lib/students.service';
import { useToast } from '@/hooks/use-toast';
import { format, addDays } from 'date-fns';

const Dashboard: React.FC = () => {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const queryClient = useQueryClient();
  const { toast } = useToast();

  const { data: lessons = [], isLoading: isLoadingLessons } = useQuery({
    queryKey: ['aulas'],
    queryFn: AulasService.listarAulas,
  });

  const { data: students = [], isLoading: isLoadingStudents } = useQuery({
    queryKey: ['alunos'],
    queryFn: listarAlunos,
  });

  const { data: studentAlerts = [] } = useQuery({
    queryKey: ['alunos', 'alertas'],
    queryFn: listarAlertasAlunos,
  });
  const lowLessonAlerts = studentAlerts.filter((a) => a.poucas_aulas);
  const idleAlerts = studentAlerts.filter((a) => a.sem_aula);

  // Derived state
  const today = new Date();
  const todayString = format(today, 'yyyy-MM-dd');
  const nextWeek = addDays(today, 7);

  const todaysLessons = lessons.filter((l) => l.data === todayString);

  const upcomingLessons = lessons.filter((l) => {
    const lessonDate = new Date(l.data);
    // Simple comparison for upcoming 7 days, excluding today if preferred, or including. 
    // Mock logic was "next 7 days".
    return lessonDate >= today && lessonDate <= nextWeek;
  });

  const activeStudents = students.filter((s) => s.status === 'Ativo');

  const pendingNotifications = lessons.filter(
    (l) => l.status === 'Agendada' && !l.notificacao_enviada
  );

  /* Mutations */
  const createLessonMutation = useMutation({
    mutationFn: AulasService.criarAula,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['aulas'] });
      queryClient.invalidateQueries({ queryKey: ['alunos'] });
      toast({ title: 'Sucesso', description: 'Aula agendada com sucesso!' });
      setIsModalOpen(false);
    },
    onError: () => {
      toast({ title: 'Erro', description: 'Erro ao agendar aula.', variant: 'destructive' });
    }
  });

  const updateLessonMutation = useMutation({
    mutationFn: ({ id, data }: { id: string; data: Partial<Aula> }) =>
      AulasService.atualizarAula(id, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['aulas'] });
      queryClient.invalidateQueries({ queryKey: ['alunos'] });
      toast({ title: 'Sucesso', description: 'Aula atualizada com sucesso!' });
      setIsModalOpen(false);
      setSelectedLesson(null);
    },
    onError: () => {
      toast({ title: 'Erro', description: 'Erro ao atualizar aula.', variant: 'destructive' });
    }
  });

  /* Handlers */
  const [selectedLesson, setSelectedLesson] = useState<Lesson | null>(null);

  const handleCreateLesson = (lessonData: Omit<Lesson, 'id'>) => {
    // The service expects an 'Aula' which includes 'id', but for creation the ID is generated by the server.
    // We pass a placeholder or cast it.
    createLessonMutation.mutate({ ...lessonData, id: '' } as Aula);
  };

  const handleSaveLesson = (lessonData: Lesson) => {
    if (selectedLesson) {
      updateLessonMutation.mutate({ id: selectedLesson.id, data: lessonData });
    } else {
      createLessonMutation.mutate({ ...lessonData, id: '' } as Aula);
    }
  };

  const handleEditLesson = (lesson: Lesson) => {
    setSelectedLesson(lesson);
    setIsModalOpen(true);
  };

  const handleConfirmLesson = (lesson: Lesson) => {
    updateLessonMutation.mutate(
      {
        id: lesson.id,
        data: {
          status: 'Confirmada',
          notificacao_enviada: true // Assuming confirming doesn't need a specific new notification trigger unless specified
        }
      },
      {
        onSuccess: () => {
          toast({
            title: 'Aula Confirmada',
            description: 'Status atualizado.',
            className: 'bg-green-50 border-green-200'
          });
        }
      }
    );
  };

  const handleCancelLesson = (lesson: Lesson) => {
    updateLessonMutation.mutate(
      {
        id: lesson.id,
        data: {
          status: 'Cancelada',
          notificacao_enviada: false, // Reset so check goes through if workflow expects it
          enviar_notificacao: true // Explicitly request notification
        }
      },
      {
        onSuccess: () => {
          toast({
            title: 'Aula Cancelada',
            description: 'Status atualizado e aluno notificado.',
            variant: 'destructive'
          });
        }
      }
    );
  };

  if (isLoadingLessons || isLoadingStudents) {
    return (
      <div className="flex justify-center items-center h-screen">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    );
  }

  return (
    <div className="space-y-8 animate-fade-in">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold font-display text-foreground">
            Dashboard
          </h1>
          <p className="text-muted-foreground mt-1">
            Bem-vindo de volta! Aqui está o resumo do dia.
          </p>
        </div>
        <div className="flex gap-3">
          <Button variant="outline" asChild>
            <Link to="/alunos">
              <Users className="h-4 w-4" />
              Novo Aluno
            </Link>
          </Button>
          <Button onClick={() => { setSelectedLesson(null); setIsModalOpen(true); }}>
            <Plus className="h-4 w-4" />
            Nova Aula
          </Button>
        </div>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <StatsCard
          title="Aulas Hoje"
          value={todaysLessons.length}
          subtitle="agendadas para hoje"
          icon={Calendar}
          variant="primary"
        />
        <StatsCard
          title="Próximos 7 dias"
          value={upcomingLessons.length}
          subtitle="aulas na semana"
          icon={Clock}
          variant="secondary"
          trend={{ value: 12, isPositive: true }} // You might want to calculate this real or remove it
        />
        <StatsCard
          title="Alunos Ativos"
          value={activeStudents.length}
          subtitle="matriculados"
          icon={Users}
          variant="accent"
        />
        <StatsCard
          title="Notificações"
          value={pendingNotifications.length}
          subtitle="pendentes de envio"
          icon={Bell}
          variant="default"
        />
      </div>

      {/* Main content grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Today's lessons */}
        <div className="lg:col-span-2 space-y-4">
          <Card>
            <CardHeader className="flex flex-row items-center justify-between pb-4">
              <div>
                <CardTitle className="flex items-center gap-2">
                  <Calendar className="h-5 w-5 text-primary" />
                  Aulas de Hoje
                </CardTitle>
              </div>
              <Button variant="ghost" size="sm" asChild>
                <Link to="/agenda">
                  Ver agenda
                  <ArrowRight className="h-4 w-4 ml-1" />
                </Link>
              </Button>
            </CardHeader>
            <CardContent className="space-y-4">
              {todaysLessons.length > 0 ? (
                todaysLessons.map((lesson) => (
                  <LessonCard
                    key={lesson.id}
                    lesson={lesson}
                    student={students.find(s => s.id === lesson.aluno_id)}
                    onEdit={handleEditLesson}
                    onConfirm={handleConfirmLesson}
                    onCancel={handleCancelLesson}
                    onReschedule={handleEditLesson}
                  />
                ))
              ) : (
                <div className="text-center py-12 text-muted-foreground">
                  <Calendar className="h-12 w-12 mx-auto mb-4 opacity-50" />
                  <p>Nenhuma aula agendada para hoje</p>
                  <Button
                    variant="link"
                    className="mt-2"
                    onClick={() => { setSelectedLesson(null); setIsModalOpen(true); }}
                  >
                    Agendar nova aula
                  </Button>
                </div>
              )}
            </CardContent>
          </Card>
        </div>

        {/* Sidebar */}
        <div className="space-y-6">
          {(lowLessonAlerts.length > 0 || idleAlerts.length > 0) && (
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="flex items-center gap-2 text-base">
                  <AlertTriangle className="h-5 w-5 text-amber-600" />
                  Atenção
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                {lowLessonAlerts.length > 0 && (
                  <div className="space-y-2">
                    <p className="text-xs font-medium uppercase text-muted-foreground">Poucas aulas</p>
                    {lowLessonAlerts.slice(0, 5).map((a) => (
                      <Link key={a.aluno_id} to="/alunos" className="flex justify-between gap-2 text-sm hover:underline">
                        <span className="truncate">{a.nome}</span>
                        <span className="text-amber-700 whitespace-nowrap">
                          {a.restam === 1 ? 'última aula' : `restam ${a.restam}`}
                        </span>
                      </Link>
                    ))}
                    {lowLessonAlerts.length > 5 && (
                      <p className="text-xs text-muted-foreground">e mais {lowLessonAlerts.length - 5}</p>
                    )}
                  </div>
                )}
                {idleAlerts.length > 0 && (
                  <div className="space-y-2">
                    <p className="text-xs font-medium uppercase text-muted-foreground">Sem aula há 15+ dias</p>
                    {idleAlerts.slice(0, 5).map((a) => (
                      <Link key={a.aluno_id} to="/alunos" className="flex justify-between gap-2 text-sm hover:underline">
                        <span className="truncate">{a.nome}</span>
                        <span className="text-orange-700 whitespace-nowrap">{a.dias_sem_aula} dias</span>
                      </Link>
                    ))}
                    {idleAlerts.length > 5 && (
                      <p className="text-xs text-muted-foreground">e mais {idleAlerts.length - 5}</p>
                    )}
                  </div>
                )}
              </CardContent>
            </Card>
          )}

          {/* Quick actions */}
          <Card variant="ocean" className="overflow-hidden">
            <CardContent className="p-6">
              <h3 className="font-display font-semibold text-lg mb-4">
                Ações Rápidas
              </h3>
              <div className="space-y-3">
                <Button
                  variant="glass"
                  className="w-full justify-start"
                  onClick={() => { setSelectedLesson(null); setIsModalOpen(true); }}
                >
                  <Plus className="h-4 w-4" />
                  Agendar aula
                </Button>
                <Button variant="glass" className="w-full justify-start" asChild>
                  <Link to="/alunos">
                    <Users className="h-4 w-4" />
                    Cadastrar aluno
                  </Link>
                </Button>
                <Button variant="glass" className="w-full justify-start" asChild>
                  <Link to="/relatorios">
                    <TrendingUp className="h-4 w-4" />
                    Ver relatórios
                  </Link>
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>

      {/* Create lesson modal */}
      <CreateLessonModal
        isOpen={isModalOpen}
        onClose={() => {
          setIsModalOpen(false);
          setSelectedLesson(null);
        }}
        onSave={handleSaveLesson}
        editLesson={selectedLesson}
      />
    </div>
  );
};

export default Dashboard;
